version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  userServiceDb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4 

  hermes.webstatus:
    image: ${DOCKER_REGISTRY-}hermeswebstatus
    build:
      context: .
      dockerfile: WebApps/Hermes.WebStatus/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  elasticsearch-data:
