version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data   

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"     
        
  userServiceDb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=UsersDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@hermes.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    depends_on:
      - userServiceDb
    restart: always
    ports:
        - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  hermes.webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=User Service Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://host.docker.internal:5157/hc
      - HealthChecksUI__HealthChecks__1__Name=Post Service Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://host.docker.internal:5240/hc

    ports:
      - "8007:80"

  ravendb:
    container_name: ravendb
    environment:
      - RAVENDB_URL=http://ravendb:8080
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_License_Eula_Accepted=true
    ports:
      - "8080:8080"
    volumes:
      - ravendb-data:/var/lib/ravendb/data